# URL de conex�o JDBC com o banco PostgreSQL localizado em localhost,
# utilizando o banco de dados chamado "alura_series"
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}

# Usu�rio utilizado pelo Spring para autentica��o no banco de dados
spring.datasource.username=${DB_USER}

# Senha do usu�rio do banco, lida a partir de uma vari�vel de ambiente
# chamada DB_PASSWORD (boa pr�tica de seguran�a)
spring.datasource.password=${DB_PASSWORD}

# Classe do driver JDBC respons�vel pela comunica��o com o PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto SQL utilizado pelo Hibernate para gerar comandos compat�veis
# com o banco de dados configurado
hibernate.dialect=org.hibernate.dialect.HSQLDialect

# Define como o Hibernate deve lidar com o esquema do banco de dados:
# update -> cria ou atualiza automaticamente tabelas e colunas
spring.jpa.hibernate.ddl-auto=update

# Habilita a exibi��o das instru��es SQL geradas pelo Hibernate no console
spring.jpa.show-sql=true

# Formata (quebra linhas e indenta) o SQL exibido no log para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true
